name: Daily Push

on:
  schedule:
    - cron: '0 9 * * *'  # Executa às 9:00 AM UTC todos os dias
  workflow_dispatch:      # Permite execução manual
  push:
    branches: [ main, master ]  # Executa quando há push para main/master

jobs:
  daily-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config user.name "Lucas Sens"
        git config user.email "lucassousasens@gmail.com"
    
    - name: Run Daily Push
      run: python daily_push.py
    
    - name: Push changes
      run: |
        git push origin HEAD:${{ github.ref }}
